[package]
name = "openguard-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "OpenGuardCLI"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
openguard-domain.workspace = true
openguard-ipc.workspace = true
openguard-windows = { path = "../openguard-windows" }
serde_json.workspace = true
uuid.workspace = true
windows-service.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
