[package]
name = "openguard-windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
openguard-detection.workspace = true
openguard-domain.workspace = true
hex.workspace = true
notify.workspace = true
quick-xml.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
winreg.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_Security_WinTrust",
    "Win32_Storage_FileSystem",
    "Win32_System_Antimalware",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_EventLog",
    "Win32_System_ProcessStatus",
    "Win32_System_Rpc",
    "Win32_System_IO",
    "Win32_System_Memory",
    "Win32_System_Threading",
] }

[lints.clippy]
all = "warn"
pedantic = "warn"

[dev-dependencies]
tempfile.workspace = true
