[package]
name = "openguard-scanner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "OpenGuardScanner"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
openguard-detection = { path = "../openguard-detection" }
serde_json.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
